name: Angular CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: npx ng build --configuration production
      - name: Log in to Cloud Foundry
        run: |
            cf login --sso -a https://api.cf.ap21.hana.ondemand.com/ -o "42635b4ctrial" -s dev

      - name: Deploy to SAP BTP CF
        run: cf push
