name: Build and Deploy to BTP Cloud Foundry

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # ✅ Use Linux for cf CLI compatibility

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: npm run build -- --configuration production

      - name: Install Cloud Foundry CLI
        run: |
          mkdir -p $HOME/bin
          curl -L "https://packages.cloudfoundry.org/stable?release=linux64-binary&version=v8" -o cf.tgz
          tar -xvzf cf.tgz -C $HOME/bin
          echo "$HOME/bin" >> $GITHUB_PATH
          chmod +x $HOME/bin/cf
          $HOME/bin/cf version

      - name: Login and Deploy to BTP
        env:
          CF_API: https://api.cf.ap21.hana.ondemand.com/ 
          CF_USERNAME: emanaymn207@gmail.com
          CF_PASSWORD: Eman207#234
          CF_ORG: 42635b4ctrial 
          CF_SPACE: dev
        run: |
          cf api $CF_API
          cf auth $CF_USERNAME $CF_PASSWORD
          cf target -o $CF_ORG -s $CF_SPACE
          cf push
